FROM wordpress:6.9.0-fpm-alpine

# Make PHP-FPM listen on TCP 9000
RUN sed -i 's|^listen = .*|listen = 0.0.0.0:9000|' /usr/local/etc/php-fpm.d/www.conf

# Remove default themes/plugins
RUN rm -rf /usr/src/wordpress/wp-content/themes/* \
    && rm -rf /usr/src/wordpress/wp-content/plugins/*

# Optional: PHP limits
COPY php/wordpress.ini /usr/local/etc/php/conf.d/wordpress.ini
